trigger:
- main
pool:
  vmImage: 'Ubuntu-latest'
variables:
  acrserviceconnection: cred-acr
  tag: '$(Build.BuildId)'
  frontendrepo: 'credpay/frontend'
  paymentrepo: 'credpay/payment'
  userrepo: 'credpay/user'
stages:
  # - stage: DockerBuild
  #   displayName: Build Docker Images
  #   jobs:
  #   - job: BuildAndPushImages
  #     displayName: Build Docker Images
  #     steps:
  #       - checkout: self
  #       - task: Docker@2
  #         inputs:
  #           containerRegistry: 'cred-acr'
  #           repository: '$(frontendrepo)'
  #           command: 'buildAndPush'
  #           Dockerfile: 'frontend-react/Dockerfile'
  #           buildContext: frontend-react
  #           tags: |
  #             $(tag)
  #             latest
  #       - task: Docker@2
  #         inputs:
  #           containerRegistry: 'cred-acr'
  #           repository: '$(paymentrepo)'
  #           command: 'buildAndPush'
  #           Dockerfile: 'payment-service/Dockerfile'
  #           buildContext: payment-service
  #           tags: |
  #             $(tag)
  #             latest
  #       - task: Docker@2
  #         inputs:
  #           containerRegistry: 'cred-acr'
  #           repository: '$(userrepo)'
  #           command: 'buildAndPush'
  #           Dockerfile: 'user-service/Dockerfile'
  #           buildContext: user-service
  #           tags: |
  #             $(tag)
  #             latest
  - stage: terraform
    displayName: Terraform Infra
    jobs:
      - job: TerraformApply
        displayName: Terraform Apply
        steps:
          - checkout: self
          - task: TerraformInstaller@1
            inputs:
              terraformVersion: 'latest'
          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'init'
              workingDirectory: 'Terraform'
              backendServiceArm: 'credpayserviceconnection'
              backendAzureRmResourceGroupName: 'CredPay'
              backendAzureRmStorageAccountName: 'credpaystorageaccount'
              backendAzureRmContainerName: 'credpaysacontainer'
              backendAzureRmKey: 'terraform.tfstate'
          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'apply'
              workingDirectory: 'Terraform'
              commandOptions: '--auto-approve'
              environmentServiceNameAzureRM: 'credpayserviceconnection'
          # - task: TerraformTask@5
          #   inputs:
          #     provider: 'azurerm'
          #     command: 'destroy'
          #     workingDirectory: 'Terraform'
          #     commandOptions: '--auto-approve'
          #     environmentServiceNameAzureRM: 'credpayserviceconnection'
















